# Generated by Django 5.0.2 on 2025-08-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cedula_profesional',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula Profesional'),
        ),
        migrations.AddField(
            model_name='user',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('cardiologia', 'Cardiología'), ('pediatria', 'Pediatría'), ('neurologia', 'Neurología'), ('dermatologia', 'Dermatología'), ('general', 'Medicina General')], max_length=50, null=True, verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='user',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Apellido'),
        ),
    ]
