# Generated by Django 5.0.2 on 2025-08-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_cedula_profesional_user_especialidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cedula_profesional',
        ),
        migrations.RemoveField(
            model_name='user',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sexo',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
