# Generated by Django 5.0.2 on 2025-10-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_especialidad_user_fecha_nacimiento_user_sexo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cedula_profesional',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cedula_valida',
            field=models.BooleanField(default=False),
        ),
    ]
