# Generated by Django 5.0.2 on 2025-10-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_cedula_profesional_user_cedula_valida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cedula_profesional',
            new_name='cedula',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cedula_valida',
        ),
    ]
