import type { Metadata } from "next";
import "./globals.css";
import type { ReactNode } from "react";
import Footer from "@/components/Footer";
import { AuthProvider } from "@/context/AuthContext";
import RegisterSW from "@/components/RegisterSW"; // ⬅ IMPORTANTE

export const metadata: Metadata = {
  title: "Sanare",
  description: "Generated by create next app",
  keywords: "next, react, app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <link rel="manifest" href="/manifest.json" />
      <body>
        <AuthProvider>
          <RegisterSW />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
