import type { Metadata } from "next";
import "./globals.css";
import type { ReactNode } from "react";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Sanare",
  description: "Generated by create next app",
  keywords: "next, react, app"
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Footer />
        {children}
      </body>
    </html>
  );
}
