# Generated by Django 5.0.2 on 2025-10-19 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('hora_apertura', models.TimeField(blank=True, null=True)),
                ('hora_cierre', models.TimeField(blank=True, null=True)),
                ('dias_habiles', models.JSONField(blank=True, default=list)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='clinicas/')),
                ('medico_responsable', models.ForeignKey(blank=True, limit_choices_to={'is_medico': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinicas_responsable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.TextField()),
                ('completada', models.BooleanField(default=False)),
                ('medico', models.ForeignKey(blank=True, limit_choices_to={'is_medico': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas_medico', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(limit_choices_to={'is_paciente': True}, on_delete=django.db.models.deletion.CASCADE, related_name='citas_paciente', to=settings.AUTH_USER_MODEL)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='citas.clinica')),
            ],
            options={
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='citas.cita')),
                ('medico', models.ForeignKey(limit_choices_to={'is_medico': True}, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_medico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('medico', models.ForeignKey(limit_choices_to={'is_medico': True}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disponibles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('medico', 'dia_semana')},
            },
        ),
    ]
