# Generated by Django 5.0.2 on 2025-08-24 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='medico',
            field=models.ForeignKey(limit_choices_to={'is_medico': True}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(limit_choices_to={'is_medico': True}, on_delete=django.db.models.deletion.CASCADE, related_name='citas_medico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='medico_responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_medico': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinicas_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='cita',
            name='estado',
        ),
        migrations.AddField(
            model_name='cita',
            name='completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cita',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='citas.clinica'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(limit_choices_to={'is_paciente': True}, on_delete=django.db.models.deletion.CASCADE, related_name='citas_paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Medico',
        ),
    ]
