# Generated by Django 5.0.2 on 2025-08-24 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_horario_medico_alter_cita_medico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_medico': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas_medico', to=settings.AUTH_USER_MODEL),
        ),
    ]
