# Generated by Django 5.0.2 on 2025-07-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='clinica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
    ]
