# Generated by Django 5.0.2 on 2025-07-23 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_clinica_especialidad_medico_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='horario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='clinicas/'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='citas.medico'),
        ),
    ]
