# Generated by Django 5.0.2 on 2025-07-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_clinica_horario_clinica_imagen_alter_cita_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinica',
            name='horario',
        ),
        migrations.AddField(
            model_name='clinica',
            name='hora_apertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='hora_cierre',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
