# Generated by Django 5.0.2 on 2025-07-26 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_remove_clinica_horario_clinica_hora_apertura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='ubicacion',
        ),
        migrations.AlterField(
            model_name='cita',
            name='clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='citas.clinica'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.medico'),
        ),
    ]
