# Generated by Django 5.0.2 on 2025-07-27 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_alter_cita_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='medico_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinicas', to='citas.medico'),
        ),
    ]
